name: analyse PR results
permissions:
  pull-requests: write
  issues: write

on:
  workflow_run:
    workflows: ["Test PR"]
    types:
      - completed

jobs:
  analyse:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIR: ${{ runner.temp }}/artifacts
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: mkdir -p "$ARTIFACTS_DIR"
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: results
          path: ${{ env.ARTIFACTS_DIR }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - run: |
          ls "$ARTIFACTS_DIR" -ltra
          cat "$ARTIFACTS_DIR/log.txt
