name: analyse PR results
permissions:
  pull-requests: write
  issues: write

on:
  workflow_run:
    workflows: ["Test PR"]
    types:
      - completed

jobs:
  analyse:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      BRANCH_SHA: ${{ github.event.workflow_run.head_sha }}
      RUN_ID: ${{ github.event.workflow_run.id }}
    steps:
      - run: mkdir -p ${{ runner.temp }}/artifacts
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: results
          path: ${{ runner.temp }}/artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - run: |
          set -x
          ARTIFACTS_DIR="${{ runner.temp }}/artifacts"
          ls "$ARTIFACTS_DIR" -ltra
          cat "$ARTIFACTS_DIR/log.txt"
          cat "$ARTIFACTS_DIR/pr.txt"
          echo $BRANCH_SHA
          cat "$ARTIFACTS_DIR/branch-sha.txt"
          echo $RUN_ID
          cat "$ARTIFACTS_DIR/run-id.txt"
