name: Test PR
permissions:
  contents: read

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_SHA: ${{ github.event.pull_request.head.sha }}
          RUN_ID: ${{ github.run_id }}
        run: |
          set -x
          echo test > log.txt
          echo $PR_NUMBER > pr.txt
          echo $BRANCH_SHA > branch-sha.txt
          echo $RUN_ID > run-id.txt
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            log.txt
            pr.txt
            branch-sha.txt
            run-id.txt
